### ISSUE TITLE
Community Exchange Introduction/Tracking

### ISSUE THREAD

**Issue by ericdrosado** [ParthJadhav/Tkinter-Designer#221]
👋 Hi @ParthJadhav ,

I am your GitHub mentor for the GitHub Education, [Community Exchange](https://airtable.com/shrRJ3AvEZQohOdGV) (CX) project. I'll be collaborating with you on preparing your repo for CX. 

You mentioned in your submission that you wanted to submit a `Learn + Collaborate` repo. This means that you would like to teach students, step by step, how to build this project as well as invite other students to collaborate and add features to this repo. I will generate issues, which will provide guidance on how to prepare your repo for a `Learn + Collaborate` CX submission on June 1, 2022.

This issue will serve as a tracking issue to track all issues related to CX. I recommend creating a new branch for every issue and opening a pull request to track changes so we can effectively collaborate with each other and merge changes when you and I feel like those changes are ready to be merged on your primary branch. 

If you have any questions or concerns, please feel free to leave a comment on this issue or any of the other issues that are generated. 

I look forward to working with you :octocat: 

## Issues
- [x] https://github.com/ParthJadhav/Tkinter-Designer/issues/222
- [x] https://github.com/ParthJadhav/Tkinter-Designer/issues/223
- [x] https://github.com/ParthJadhav/Tkinter-Designer/issues/224
- [x] https://github.com/ParthJadhav/Tkinter-Designer/issues/225

**Comment by ParthJadhav** [comment]
Hey @ericdrosado ,

Nice to hear from you, I'll start working on the changes and suggestions.

**Comment by ParthJadhav** [comment]
@ericdrosado completed & merged all the tasks 🚀

**Comment by ericdrosado** [comment]
Thank you for working through the issues @ParthJadhav. For now, please leave this issue open. I'll contact you this week with how to add your project to CX. 🎉

**Comment by ParthJadhav** [comment]
Cool, Thanks !
